apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-service
  labels:
    app: music-service

spec:
  selector:
    matchLabels:
      app: music-service
  template:
    metadata:
      labels:
        app: music-service
    spec:
      containers:
        - name: music-service
          image: music-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 8080
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 15
          volumeMounts:
            - name: music-config-volume
              mountPath: /workspace/config
      volumes:
        - name: music-config-volume
          configMap:
            name: music-config