apiVersion: v1
kind: Service
metadata:
  name: music-service
  labels:
    app: music-service
spec:
  type: ClusterIP
  selector:
    app: music-service
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP